/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Jonathan Pimentel
 */
public class Frm_Bloc extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Bloc
     */
    public Frm_Bloc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfcEmergente = new javax.swing.JFileChooser();
        jopMensaje = new javax.swing.JOptionPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jmbBarra = new javax.swing.JMenuBar();
        jmbArchivo = new javax.swing.JMenu();
        miNuevo = new javax.swing.JMenuItem();
        miAbrir = new javax.swing.JMenuItem();
        miGuardar = new javax.swing.JMenuItem();
        miGuardarComo = new javax.swing.JMenuItem();
        jmbEdicion = new javax.swing.JMenu();
        miMay = new javax.swing.JMenuItem();
        miMin = new javax.swing.JMenuItem();
        miNor = new javax.swing.JMenuItem();
        miNe = new javax.swing.JMenuItem();
        miCur = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jmbArchivo.setText("Archivo");

        miNuevo.setText("Nuevo");
        jmbArchivo.add(miNuevo);

        miAbrir.setText("Abrir");
        miAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAbrirActionPerformed(evt);
            }
        });
        jmbArchivo.add(miAbrir);

        miGuardar.setText("Guardar");
        jmbArchivo.add(miGuardar);

        miGuardarComo.setText("Guardar como...");
        jmbArchivo.add(miGuardarComo);

        jmbBarra.add(jmbArchivo);

        jmbEdicion.setText("Edición");

        miMay.setText("Mayúscula");
        jmbEdicion.add(miMay);

        miMin.setText("Minúcula");
        jmbEdicion.add(miMin);

        miNor.setText("Normal");
        jmbEdicion.add(miNor);

        miNe.setText("Negrita");
        jmbEdicion.add(miNe);

        miCur.setText("Cursiva");
        jmbEdicion.add(miCur);

        jmbBarra.add(jmbEdicion);

        setJMenuBar(jmbBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAbrirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Bloc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Bloc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Bloc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Bloc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Bloc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JFileChooser jfcEmergente;
    public javax.swing.JMenu jmbArchivo;
    public javax.swing.JMenuBar jmbBarra;
    public javax.swing.JMenu jmbEdicion;
    public javax.swing.JOptionPane jopMensaje;
    public javax.swing.JMenuItem miAbrir;
    public javax.swing.JMenuItem miCur;
    public javax.swing.JMenuItem miGuardar;
    public javax.swing.JMenuItem miGuardarComo;
    public javax.swing.JMenuItem miMay;
    public javax.swing.JMenuItem miMin;
    public javax.swing.JMenuItem miNe;
    public javax.swing.JMenuItem miNor;
    public javax.swing.JMenuItem miNuevo;
    public javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
